[package]
name = "tiny-docker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tar = "0.4.40"
flate2 = "1.0.28"
libc = "0.2.151"
errno = "0.3.8"
nix = { version = "0.27.1", features = ["process"] }
